### ISSUE TITLE
can't update value to sharepoint list

### ISSUE THREAD

**Issue by limfoo** [MicrosoftDocs/powerapps-docs.zh-cn#4]
using this approach I can't update value to sharepoint list

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [在画布应用中创建依赖项下拉列表 - Power Apps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by srvbpigh** [comment]
Hello, @limfoo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @limfoo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerapps-docs/issues/1378. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
